baseURL = "https://flow.visionhope.cn"
defaultContentLanguage = "zh-cn"
hasCJKLanguage = true
theme = "LoveIt"

[author]
name = "Vision"

[languages.zh-cn]
disabled = false
languageCode = 'zh-CN'
languageDirection = 'ltr'
languageName = '简体中文'
title = '自闭者的喃喃'
name = "Vision"
weight = 1

[languages.en]
disabled = false
languageCode = 'en'
languageDirection = 'ltr'
languageName = 'English'
title = 'Whisper of the Autist'
weight = 2


[[languages.zh-cn.menu.main]]
weight = 1
identifier = "posts"
name = "文章"
url = "/posts/"

[[languages.zh-cn.menu.main]]
weight = 2
identifier = "notes"
name = "笔记"
url = "/notes/"

[[languages.zh-cn.menu.main]]
weight = 3
identifier = "reviews"
name = "评论"
url = "/reviews/"


[[languages.en.menu.main]]
weight = 1
identifier = "posts"
name = "Posts"
url = "/posts/"


[params]
version = "0.2.X"               # LoveIt 主题版本

[params.analytics]
enable = true

[params.analytics.google]
id = "G-PG2EZ3Q1QT"
anonymizeIP = true # 是否匿名化用户 IP

[markup.highlight]
noClasses = false
