baseURL = "https://flow.visionhope.cn"
defaultContentLanguage = "zh-cn"
languageCode = "zh-CN"
hasCJKLanguage = true
title = "自闭者的喃喃"
theme = "LoveIt"

[author]
name  = "Vision"


[params]
version = "0.2.X"               # LoveIt 主题版本

[params.analytics]
enable = true

[params.analytics.google]
id = "G-PG2EZ3Q1QT"
anonymizeIP = true # 是否匿名化用户 IP

[markup.highlight]
noClasses = false

[[menu.main]]
name = '文章'
identifier = 'posts'
url = '/posts/'

[[menu.main]]
name = '笔记'
identifier = 'notes'
url = '/notes/'

[[menu.main]]
name = '评论'
identifier = 'reviews'
url = '/reviews/'
